### PR TITLE
fix(frontend): prevent dependency dialog overflow and enable proper s…

### LINKED ISSUE #1141: [Bug] 前置模组对话框可能溢出
### 问题描述

Image

### 操作系统

macOS

### SJMCL 版本（可选）

_No response_

### 复现步骤

见上

### 预期行为

应该在列表到达一定长度后开始 modal 内滚动

modal 的最大长度类似创建实例和资源下载 modal（ModalContent 上加 h=100% 的效果）

### 环境信息（可选）

_No response_

### 补充信息（可选）

_No response_

### PR DESCRIPTION
**Pull request by baiyuansjtu**
…crolling

### Checklist

- [ ] Changes have been tested locally and work as expected.
- [ ] All tests in workflows pass successfully.
- [ ] Documentation has been updated if necessary.
- [ ] Code formatting and commit messages align with the project's conventions.
- [ ] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 🛠 Refactoring
- [ ] ⚡️ Performance improvement
- [ ] 🌐 Internationalization
- [ ] 📄 Documentation improvement
- [ ] 🎨 Code style optimization
- [ ] ❓ Other (Please specify below)

### Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - e.g. close #xxxx, fix #1141 

### Description

> - Please insert your description here and provide info about the "what" this PR is solving.

### Additional Context

> - Add any other relevant information or screenshots here.

### CODE REVIEW

File: src/components/modals/alert-resource-dependency-modal.tsx [hunk 1]
```diff
@@ -200,7 +200,7 @@ const AlertResourceDependencyModal: React.FC<
   return (
     <Modal size={{ base: "md", lg: "lg", xl: "xl" }} {...modalProps}>
       <ModalOverlay />
-      <ModalContent>
```
Comment (UNIkeEN) [inline src/components/modals/alert-resource-dependency-modal.tsx:203]: 别的 modal 有加这个 h=80% 吗，我只见过 100% 的来着（？）

Comment (baiyuansjtu) [reply src/components/modals/alert-resource-dependency-modal.tsx:203]: 这里100太高了，80才是和上级modal一样高的

Comment (UNIkeEN) [reply src/components/modals/alert-resource-dependency-modal.tsx:203]: > 这里100太高了，80才是和上级modal一样高的

项目里有其他 modal 用了 80% 吗
