### PR TITLE
fix(backend): custom window title persistence

### LINKED ISSUE #458: [Bug] 自定义窗口标题可被覆盖
### Description

使用“自定义窗口标题”功能时（仅限Windows），进入游戏后操作（如点击“单人游戏”），窗口标题会被覆盖为默认

### OS

Windows 11

### SJMCL Version (Optional)

_No response_

### Reproduction

1. 设置“自定义窗口标题”后进入游戏
2. 点击“单人游戏”

### Expected Behavior

自定义窗口标题保持不变

### Environment (Optional)

_No response_

### Additional context (Optional)

_No response_

### PR DESCRIPTION
**Pull request by ModistAndrew**
### Checklist

- [x] Changes have been tested locally and work as expected.
- [ ] All tests in workflows pass successfully.
- [ ] Documentation has been updated if necessary.
- [x] Code formatting and commit messages align with the project's conventions.
- [x] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 🛠 Refactoring
- [ ] ⚡️ Performance improvement
- [ ] 🌐 Internationalization
- [ ] 📄 Documentation improvement
- [ ] 🎨 Code style optimization
- [ ] ❓ Other (Please specify below)

### Related Issues

fix #458

### Description

Fix custom window title persistence with polling thread.

### Additional Context

None

### CODE REVIEW

File: src-tauri/src/launch/helpers/process_monitor.rs [hunk 1]
```diff
@@ -148,9 +149,24 @@ pub async fn monitor_process(
     .listen_from_output()
   });
 
+  // polling thread (for changing window title, etc.)
```
Comment (UNIkeEN) [inline src-tauri/src/launch/helpers/process_monitor.rs:154]: 这一段代码里换标题的部分不加 windows 平台编译条件宏吗

另外请问这里的 stop_polling_flag 可以支持多个实例同时运行吗

File: src-tauri/src/launch/commands.rs [hunk 2]
```diff
@@ -303,8 +304,7 @@ pub async fn launch_game(
 
   // set process priority and window title (if error, keep slient)
   let _ = set_process_priority(pid, &game_config.performance.process_priority);
-  let _ = !game_config.game_window.custom_title.trim().is_empty()
-    && change_process_window_title(pid, &game_config.game_window.custom_title).is_err();
+  let _ = !game_config.game_window.custom_title.trim().is_empty();
```
Comment (UNIkeEN) [inline src-tauri/src/launch/commands.rs]: 这一行现在还有用吗

File: src-tauri/src/launch/helpers/process_monitor.rs (hunk 1 above)
Comment (ModistAndrew) [reply src-tauri/src/launch/helpers/process_monitor.rs:154]: 理论上可以有其他平台，只是还不支持？
应该是每个实例对应一个process monitor吧

File: src-tauri/src/launch/helpers/process_monitor.rs [hunk 3]
```diff
@@ -148,9 +149,24 @@ pub async fn monitor_process(
...
+  let stop_polling_flag = Arc::new(AtomicBool::new(false));
+  let _ = {
+    let stop_polling_flag = stop_polling_flag.clone();
+    let pid = child.id();
+    let custom_title = custom_title.to_string();
+    thread::spawn(move || {
+      while !stop_polling_flag.load(Ordering::SeqCst) {
+        thread::sleep(std::time::Duration::from_millis(2000));
```
Comment (UNIkeEN) [inline src-tauri/src/launch/helpers/process_monitor.rs]: 这个 2000 做成这个文件最开始的 const 吧，比如 POLLING_OPERATION_INTERVAL 啥的

**Review by UNIkeEN — APPROVED** [review]

**Review by baiyuansjtu — APPROVED** [review]
