### PR TITLE
Fix/xsts xerr handling

### LINKED ISSUE #1529: [Bug] 在登录微软账号时，未对 XSTS 登录时的 XErr 做处理
### Description

你好！我刚刚查阅了一下你的代码，发现并未在登录 XSTS 时对部分显示的 XErr 做处理。。
代码如下：
https://github.com/UNIkeEN/SJMCL/blob/main/src-tauri/src/account/helpers/microsoft/oauth.rs#L78
然而，在登录微软账号时，几乎可以肯定是会遇到一些不为人知的错误的，比如说未成年家长管控、账号封禁、存在风险、尚未验证等的情况均有可能会造成 XSTS 登录失败。。
我很久以前写的启动器源代码可以给你看看：（里面记录了我从网络上搜集的所有 XErr 的环节。。）
https://github.com/CandySharkStudio/PCL.Nova.Plus/blob/main/module/mmcll/account_method.go#L232
哦对了，这个 XErr 代码在微软官方文档里可能没有，因为我 bing 了很久也没找到。。我这是通过对 stackoverflow 上暂时翻到的一些，希望能对你有用！！如果你对我发的 XErr 值还有补充，我也欢迎你来为我提 issue！

### OS

几乎所有

### SJMCL Version (Optional)

1.0.0-Beta-5

### Reproduction

1. 使用黑卡或者废弃的账号登录微软
2. XErr 出现！但是 SJMCL 并未作出提醒。。

### Expected Behavior

应该做出提醒

### Environment (Optional)

_No response_

### Additional context (Optional)

_No response_

### PR DESCRIPTION
**Pull request by zaixiZaixiSJTU**
### Checklist

- [ ] Changes have been tested locally and work as expected.
- [ ] All tests in workflows pass successfully.
- [ ] Documentation has been updated if necessary.
- [ ] Code formatting and commit messages align with the project's conventions.
- [ ] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [x] 🐞 Bug fix

### Related Issues

>  fix #1529 

### Description

> - 来点测试

## Summary by Sourcery

Improve handling of Microsoft XSTS authentication failures by mapping service error codes to explicit account error types and surfacing them to the client.

Bug Fixes:
- Handle non-success XSTS token responses by parsing error payloads and returning specific account errors instead of generic network or parse failures.

Enhancements:
- Introduce dedicated XSTS-related error variants in both Rust and TypeScript account error enums to distinguish different Xbox account states.
- Add deserialization support for XSTS error responses and wire it into the XSTS token fetching logic.
- Extend localization entries to cover new XSTS error messages in multiple languages.

### CODE REVIEW

**Review by UNIkeEN — CHANGES_REQUESTED** [review]
为保持一致，请删除新增 error 描述的所有句号

File: src-tauri/src/account/helpers/microsoft/oauth.rs [hunk 1]
```diff
@@ -95,19 +97,41 @@ async fn fetch_xsts_token(app: &AppHandle, xbl_token: String) -> SJMCLResult<(St
     )
     .send()
     .await
-    .map_err(|_| AccountError::NetworkError)?
+    .map_err(|_| AccountError::NetworkError)?;
+
+  //refer to https://github.com/PrismarineJS/prismarine-auth/blob/master/src/common/Constants.js
```
Comment (UNIkeEN) [inline src-tauri/src/account/helpers/microsoft/oauth.rs]:
```
// ref: https://github.com/PrismarineJS/prismarine-auth/blob/b795199dc5fa26059655bb1bc91c7f7f2733b232/src/common/Constants.js#L51
```

**Comment by UNIkeEN** [comment]
另外，下次建议每一个新功能从最新的 main 新拉分支，不然容易遇到冲突哦

**Review by UNIkeEN — APPROVED** [review]
