### PR TITLE
fix(account): YGG OAuth profile retrieval is incomplete; improper handle of OAuth cancellation

### LINKED ISSUE #878: [Bug] OAuth 登录方式角色信息不完整
### Description

https://github.com/UNIkeEN/SJMCL/blob/ac3797dbbdabd6a3ddf21cb63af975ce7b2b9af1/src-tauri/src/account/helpers/authlib_injector/oauth.rs#L118-L120

从 ID Token 中解析的 `selectedProfile` 可能是不完整的，例如只包含 `id` 和 `name`，这种情况下将无法获取角色皮肤。应当参考传统密码登录方式

https://github.com/UNIkeEN/SJMCL/blob/ac3797dbbdabd6a3ddf21cb63af975ce7b2b9af1/src-tauri/src/account/helpers/authlib_injector/password.rs#L93-L106

从 `selectedProfile` 提取 UUID 后再调用 `get_profile` 从 `/sessionserver/session/minecraft/profile/{uuid}` 获取完整角色信息。

### OS

macOS Sequoia 15.5

### SJMCL Version (Optional)

_No response_

### Reproduction

使用 OAuth 登录方式添加 MUA 皮肤站角色，启动器内无法正常显示角色皮肤，游戏内正常。

### Expected Behavior

使用 OAuth 登录方式添加 MUA 皮肤站角色，启动器内正常显示角色皮肤。

### Environment (Optional)

_No response_

### Additional context (Optional)

_No response_

### LINKED ISSUE #879: [Bug] 当 OAuth 授权流程中止后，启动器仍继续轮询接口
### Description

当 OAuth 授权流程中止后，启动器仍在继续轮询 Token Endpoint 直至超时。

### OS

macOS Sequoia 15.5

### SJMCL Version (Optional)

_No response_

### Reproduction

https://github.com/user-attachments/assets/ca0eae95-4282-4bd5-a89a-cc86a873c7c5

### Expected Behavior

用户中止 OAuth 授权流程后，启动器从 Token Endpoint 是可以获得这一信息的，此时应停止轮询，返回 Cancelled 提示。

### Environment (Optional)

_No response_

### Additional context (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Reqwey**
### Checklist

- [ ] Changes have been tested locally and work as expected.
- [ ] All tests in workflows pass successfully.
- [ ] Documentation has been updated if necessary.
- [ ] Code formatting and commit messages align with the project's conventions.
- [ ] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [x] 🛠 Refactoring
- [ ] ⚡️ Performance improvement
- [ ] 🌐 Internationalization
- [ ] 📄 Documentation improvement
- [ ] 🎨 Code style optimization
- [ ] ❓ Other (Please specify below)

### Related Issues

> - fix #878 
> - fix #879 

### Description

> - Please insert your description here and provide info about the "what" this PR is solving.

### Additional Context

> - 本次更新同时加入了 MUA 的专属 `client_id`

### CODE REVIEW

File: src-tauri/src/account/helpers/authlib_injector/oauth.rs [hunk 1]
```diff
@@ -55,15 +56,18 @@ async fn fetch_jwks(app: &AppHandle, jwks_uri: String) -> SJMCLResult<Value> {
 pub async fn device_authorization(
   app: &AppHandle,
   openid_configuration_url: String,
-  client_id: String,
+  client_id: Option<u64>,
```
Comment (hans362) [inline src-tauri/src/account/helpers/authlib_injector/oauth.rs]: 根据 https://datatracker.ietf.org/doc/html/rfc6749#section-2.2 ，`client_id` 的数据类型是字符串，不一定是无符号整数。

File: src-tauri/src/account/helpers/authlib_injector/info.rs [hunk 2]
```diff
@@ -29,13 +29,10 @@ pub async fn fetch_auth_server_info(
...
 
-        if client_id.is_empty() {
+        if client_id.is_none() {
           let response = client.get(&openid_configuration_url).send().await?;
           let data: serde_json::Value = response.json().await.map_err(|_| AccountError::Invalid)?;
-          client_id = data["shared_client_id"]
-            .as_str()
-            .unwrap_or_default()
-            .to_string();
+          client_id = data["shared_client_id"].as_u64();
```
Comment (hans362) [inline src-tauri/src/account/helpers/authlib_injector/info.rs]: 响应中的 `shared_client_id` 类型是字符串，直接 `as_u64` 的结果是 None，直接不可用了。另外，根据 https://datatracker.ietf.org/doc/html/rfc6749#section-2.2 ，`client_id` 的数据类型是字符串，不一定是无符号整数。

File: src-tauri/src/account/helpers/authlib_injector/password.rs [hunk 3]
```diff
@@ -167,13 +138,21 @@ pub async fn refresh(
...
     content.selected_profile.ok_or(AccountError::ParseError)?.id,
-    player.auth_account.clone().unwrap_or_default(),
-    player.password.clone().unwrap_or_default(),
+  )
+  .await?;
+
+  parse_profile(
+    app,
+    &profile,
+    Some(player.access_token.clone().unwrap_or_default()),
```
Comment (hans362) [inline src-tauri/src/account/helpers/authlib_injector/password.rs]: `player.access_token` 不对吧？刷新之后要更新 `access_token` 的，应该是 `content.access_token`

Comment (Reqwey) [reply src-tauri/src/account/helpers/authlib_injector/password.rs]: 嗷嗷不好意思写错了
