### PR TITLE
fix(frontend): add handleClose in sync-config-modals

### LINKED ISSUE #532: [Bug] 启动器设置同步导入，modal关闭再打开内容没清空
### Description

启动器设置同步导入，modal关闭再打开令牌没清空
Image

### OS

Windows 10

### SJMCL Version (Optional)

_No response_

### Reproduction

启动器设置同步导入，modal关闭再打开，令牌没清空

### Expected Behavior

应该清空内容

### Environment (Optional)

_No response_

### Additional context (Optional)

_No response_

### PR DESCRIPTION
**Pull request by HsxMark**
### Checklist

- [x] Changes have been tested locally and work as expected.
- [x] All tests in workflows pass successfully.
- [x] Documentation has been updated if necessary.
- [x] Code formatting and commit messages align with the project's conventions.
- [x] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 🛠 Refactoring
- [ ] ⚡️ Performance improvement
- [ ] 🌐 Internationalization
- [ ] 📄 Documentation improvement
- [ ] 🎨 Code style optimization
- [ ] ❓ Other (Please specify below)

### Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.

fix #532 

### Description

> - Please insert your description here and provide info about the "what" this PR is solving.

### Additional Context

> - Add any other relevant information or screenshots here.

### CODE REVIEW

File: src/components/modals/sync-config-modals.tsx [hunk 1]
```diff
@@ -139,10 +144,14 @@ export const SyncConfigImportModal: React.FC<SyncConfigModalProps> = ({
...
     }
     setIsLoading(false);
-  }, [modalProps, setConfig, toast, token]);
+  }, [handleCloseModal, setConfig, toast, token]);
 
   return (
-    <Modal size={{ base: "md", lg: "lg", xl: "xl" }} {...modalProps}>
+    <Modal
+      size={{ base: "md", lg: "lg", xl: "xl" }}
+      isOpen={modalProps.isOpen}
```
Comment (UNIkeEN) [inline src/components/modals/sync-config-modals.tsx]: 为什么要把 isOpen 拎出来然后删除 modalProps？？在最后覆盖 onClose 不就行了

File: src/components/modals/sync-config-modals.tsx [hunk 2]
```diff
@@ -129,8 +135,7 @@ export const SyncConfigImportModal: React.FC<SyncConfigModalProps> = ({
         title: response.message,
         status: "success",
       });
-      setToken("");
-      modalProps.onClose();
+      handleCloseModal();
```
Comment (UNIkeEN) [inline src/components/modals/sync-config-modals.tsx:137]: 此处和 146 行有逻辑冗余，请同步修改 146 行

File: src/components/modals/sync-config-modals.tsx [hunk 3]
```diff
@@ -118,6 +118,12 @@ export const SyncConfigImportModal: React.FC<SyncConfigModalProps> = ({
   const [token, setToken] = useState("");
   const [isLoading, setIsLoading] = useState(false);
 
+  const handleCloseModal = useCallback(() => {
+    setToken("");
+    setIsLoading(false);
+    modalProps.onClose();
+  }, [modalProps]);
+
```
Comment (UNIkeEN) [inline src/components/modals/sync-config-modals.tsx:127]: 这是个函数 为什么不放在所有变量和state定义之后？

File: src/components/modals/sync-config-modals.tsx [hunk 4]
```diff
@@ -117,32 +117,43 @@ export const SyncConfigImportModal: React.FC<SyncConfigModalProps> = ({
...
+        handleCloseModal();
+      } else {
+        toast({
+          title: response.message,
+          description: response.details,
+          status: "error",
+        });
+      }
+    } finally {
+      if (!isLoading) setIsLoading(false);
```
Comment (UNIkeEN) [inline src/components/modals/sync-config-modals.tsx]: ？？？
