### PR TITLE
fix(frontend): add Empty in widget,  add missing icon in screenshots,…

### LINKED ISSUE #213: [Feature] 实例模组小组件显示优化
### 相关问题（可选）

1. 希望在没有模组时显示无数据，和其他组件保持一致

Image

2. 希望对没有启用的模组图标也显示为灰色，和模组页面保持一致；

Image

Image

### 解决方案

见上

### 替代方案（可选）

_No response_

### 补充信息（可选）

_No response_

### PR DESCRIPTION
**Pull request by HsxMark**
… adjust form in modwidget

### Checklist

- [x] Changes have been tested locally and work as expected.
- [x] All tests in workflows pass successfully.
- [x] Documentation has been updated if necessary.
- [x] Code formatting and commit messages align with the project's conventions.
- [x] Comments have been added for any complex logic or functionality if possible.

### This PR is a ..

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 🛠 Refactoring
- [ ] ⚡️ Performance improvement
- [ ] 🌐 Internationalization
- [ ] 📄 Documentation improvement
- [ ] 🎨 Code style optimization
- [ ] ❓ Other (Please specify below)

### Related Issues

> - fix #213 

### Description

> - Please insert your description here and provide info about the "what" this PR is solving.

### Additional Context

截屏2025-02-26 00 10 49

截屏2025-02-26 00 10 49
截屏2025-02-26 00 12 06

### CODE REVIEW

File: src/components/instance-widgets.tsx [hunk 1]
```diff
@@ -222,39 +224,50 @@ export const InstanceModsWidget = () => {
...
+            >
+              <HStack spacing={1.5}>
+                <Icon as={LuArrowRight} />
+                <Text>{t("InstanceWidgets.mods.manage")}</Text>
+              </HStack>
+            </Button>
+          </VStack>
+        </HStack>
+      ) : (
+        <Empty withIcon={false} size="sm" />
```
Comment (UNIkeEN) [inline src/components/instance-widgets.tsx:249]: 显示 Empty 的同时没让你删除管理按钮啊，这不符合交互设计逻辑吧

Comment (HsxMark) [reply src/components/instance-widgets.tsx:249]: > 显示 Empty 的同时没让你删除管理按钮啊，这不符合交互设计逻辑吧

截屏2025-02-26 00 56 08
已修复

**Comment by UNIkeEN** [comment]
另外在这里加不透明度肯定不好看（图标会重叠），请删掉

...还是那句话我特地写了灰色）

**Comment by HsxMark** [comment]
> 另外在这里加不透明度肯定不好看（图标会重叠），请删掉
> 
> ...还是那句话我特地写了灰色）

截屏2025-02-26 07 22 25
已删除排序功能
已删除透明度

**Comment by UNIkeEN** [comment]
> 关于截图组件的fix不错

我收回这句话，主线的合并更改已撤回

image

你居然觉得这样是合理的设计？
